# If you update this file, you must consult research_core.md to see whether research_core.md needs to be updated. research_core.md must not exceed 100 lines.
"""Legacy reflection API metadata projected from the canonical definition."""

from ..workflows import reflection, research_contracts
from .workflow_schema import Workflow, validate_workflow

CORE_LENSES = research_contracts.CORE_LENSES
CORE_LENS_IDS = research_contracts.CORE_LENS_IDS
ROSTER_SIZE = research_contracts.ROSTER_SIZE
REFLECTION_IDLE_RECOMMEND_NEW_TERMINAL_THRESHOLD = research_contracts.REFLECTION_IDLE_RECOMMEND_NEW_TERMINAL_THRESHOLD
REFLECTION_NUDGE_NEW_TERMINAL_THRESHOLD = research_contracts.REFLECTION_NUDGE_NEW_TERMINAL_THRESHOLD
REFLECTION_BLOCK_NEW_TERMINAL_THRESHOLD = research_contracts.REFLECTION_BLOCK_NEW_TERMINAL_THRESHOLD
RETURN_TO_REFLECTING = reflection.RETURN_TO_REFLECTING
RETURN_TO_SYNTHESIZING = reflection.RETURN_TO_SYNTHESIZING
RETURN_TO_CONSOLIDATING = reflection.RETURN_TO_CONSOLIDATING
REFLECTION_WORKFLOW = Workflow(reflection.REFLECTION, reflection.METADATA)
REFLECTION_TERMINAL_STATUSES = REFLECTION_WORKFLOW.terminal_statuses
REFLECTION_TRANSITION_VALUES = REFLECTION_WORKFLOW.transition_names
validate_workflow(REFLECTION_WORKFLOW)

__all__ = ["CORE_LENSES", "CORE_LENS_IDS", "ROSTER_SIZE", "REFLECTION_WORKFLOW", "REFLECTION_TERMINAL_STATUSES",
           "REFLECTION_TRANSITION_VALUES", "REFLECTION_IDLE_RECOMMEND_NEW_TERMINAL_THRESHOLD",
           "REFLECTION_NUDGE_NEW_TERMINAL_THRESHOLD", "REFLECTION_BLOCK_NEW_TERMINAL_THRESHOLD",
           "RETURN_TO_REFLECTING", "RETURN_TO_SYNTHESIZING", "RETURN_TO_CONSOLIDATING"]
