import Lean
import Workflow
import Invariants
import Admission
import ReviewClaims
import SessionOwnership
import WorkflowDependencies
import IdentityCredentials
import ScopeAuthority
import Fleet
import FleetWorkflow
import FleetLease
import FleetRelease
import BackendProviderBoundary
import BackendRelay
import BackendAuthority
import BackendEvents
import BackendStorage
import RunnerOwnership
import RunnerSettlement

open Lean Elab Command

/-!
Fail closed on unfinished proofs and project-specific axioms. Audit every
declaration in the model namespace, including definitions and helper theorems,
so adding a theorem cannot accidentally omit it from the audit.
-/
run_cmd do
  let required : Array Name := #[
    `Merv.BackendAuthority.arbitrary_trace_dispatch_safety,
    `Merv.BackendAuthority.arbitrary_composed_trace_cannot_revive_credential,
    `Merv.BackendAuthority.fresh_prepare_then_dispatch_progress,
    `Merv.BackendAuthority.arbitrary_trace_consumed_cannot_dispatch,
    `Merv.BackendAuthority.arbitrary_trace_retired_provider_cannot_recover,
    `Merv.BackendAuthority.credential_requires_live_exact_record,
    `Merv.BackendAuthority.session_holder_requires_current_records,
    `Merv.BackendAuthority.arbitrary_scope_trace_cannot_resurrect_source,
    `Merv.BackendAuthority.wrong_identity_denied,
    `Merv.BackendAuthority.provider_replacement_denied,
    `Merv.BackendAuthority.one_shot_dispatch,
    `Merv.BackendAuthority.authorized_dispatch_progress,
    `Merv.BackendAuthority.provider_mutant_counterexample,
    `Merv.BackendEvents.cursor_never_passes_committed_head,
    `Merv.BackendEvents.publisher_change_iff_event,
    `Merv.BackendEvents.exactly_once_durable_prefix,
    `Merv.BackendEvents.no_duplicate_effect,
    `Merv.BackendEvents.no_uncommitted_effect,
    `Merv.BackendEvents.no_lost_processed_effect,
    `Merv.BackendEvents.trace_effects_monotone,
    `Merv.BackendEvents.recovery_completes_backlog,
    `Merv.BackendEvents.stale_failure_is_inert,
    `Merv.BackendEvents.recover_reaches_head,
    `Merv.BackendEvents.commit_replay_inert,
    `Merv.BackendEvents.external_redelivery_counterexample,
    `Merv.BackendEvents.commit_order_counterexample,
    `Merv.BackendStorage.arbitrary_trace_immutable_binding,
    `Merv.BackendStorage.arbitrary_trace_immutable_object,
    `Merv.BackendStorage.arbitrary_trace_immutable_ticket,
    `Merv.BackendStorage.arbitrary_trace_no_unauthorized_attachment,
    `Merv.BackendStorage.arbitrary_trace_content_and_project_binding,
    `Merv.BackendStorage.commit_new_attachment_authorized,
    `Merv.BackendStorage.existing_commit_exact_replay,
    `Merv.BackendStorage.positive_recovery,
    `Merv.BackendStorage.outage_retry_retains_state,
    `Merv.BackendStorage.lost_commit_keeps_persistence,
    `Merv.BackendStorage.stale_authorization_counterexample,
    `Merv.BackendStorage.revocation_does_not_revoke_capability,
    `Merv.BackendStorage.capability_expiry,
    `Merv.BackendRelay.arbitrary_trace_one_callback,
    `Merv.BackendRelay.unsettled_retains_reservation,
    `Merv.BackendRelay.malformed_usage_retains_charge,
    `Merv.BackendRelay.valid_usage_settles,
    `Merv.BackendRelay.refusal_refunds,
    `Merv.BackendRelay.crash_before_callback_keeps_charge,
    `Merv.BackendRelay.trace_original_day,
    `Merv.BackendRelay.zero_default_counterexample,
    `Merv.BackendRelay.arbitrary_trace_at_most_one_commit,
    `Merv.BackendRelay.forwarded_usage_is_durable,
    `Merv.BackendRelay.committed_amount_survives_arbitrary_retries,
    `Merv.BackendRelay.wrong_request_cannot_settle,
    `Merv.BackendRelay.crash_after_commit_keeps_usage,
    `Merv.BackendRelay.crash_before_commit_cannot_forward_usage,
    `Merv.BackendProviderBoundary.Durable.terminal_sound,
    `Merv.BackendProviderBoundary.Durable.capacity_safe,
    `Merv.BackendProviderBoundary.Durable.stale_callbacks_preserve_successor,
    `Merv.BackendProviderBoundary.Durable.admission_stays_closed,
    `Merv.BackendProviderBoundary.Durable.settlement_wakes_cleanup,
    `Merv.BackendProviderBoundary.Durable.late_settlement_cleanup_progress,
    `Merv.BackendProviderBoundary.Durable.crash_and_recovery_do_not_settle,
    `Merv.BackendProviderBoundary.Durable.normal_progress,
    `Merv.BackendProviderBoundary.current_provider_breaks_capacity,
    `Merv.BackendProviderBoundary.current_provider_breaks_terminal_soundness,
    `Merv.BackendProviderBoundary.guarded_trace_capacity,
    `Merv.BackendProviderBoundary.guarded_cleanup_progress,
    `Merv.BackendProviderBoundary.guarded_no_create_cleanup_progress,
    `Merv.BackendProviderBoundary.fleet_refinement_transfers_capacity,
    `Merv.BackendProviderBoundary.current_trace_has_no_safe_refinement,
    `Merv.Workflow.stale_revision_rejected,
    `Merv.Workflow.matching_replay_unchanged,
    `Merv.Workflow.conflicting_replay_unchanged,
    `Merv.Workflow.terminal_store_unchanged,
    `Merv.Workflow.commit_uses_allowed_edge,
    `Merv.Workflow.replay_at_most_once,
    `Merv.Workflow.commit_records_receipt,
    `Merv.Workflow.commit_then_retry_unchanged,
    `Merv.Workflow.receipt_preserved,
    `Merv.Workflow.trace_preserves_receipt,
    `Merv.Workflow.existing_receipt_never_commits,
    `Merv.Workflow.commit_then_interleaved_retry_cannot_commit,
    `Merv.Workflow.step_effect_shape,
    `Merv.Workflow.step_revision_monotone,
    `Merv.Workflow.step_history_revision_consistent,
    `Merv.Workflow.step_receipts_history_consistent,
    `Merv.Workflow.trace_revision_monotone,
    `Merv.Workflow.trace_history_revision_consistent,
    `Merv.Workflow.trace_receipts_history_consistent,
    `Merv.Workflow.selected_edge_is_declared,
    `Merv.Workflow.validated_terminal_has_no_edge,
    `Merv.Workflow.step_state_declared,
    `Merv.Workflow.trace_state_declared,
    `Merv.Admission.preflight_denial_unchanged,
    `Merv.Admission.denied_replay_unchanged,
    `Merv.Admission.fresh_guard_failure_unchanged,
    `Merv.Admission.late_withdrawal_rolls_back,
    `Merv.Admission.fromCore_committed,
    `Merv.Admission.committed_requires_admission,
    `Merv.ReviewClaims.pinned_immutable,
    `Merv.ReviewClaims.submitted_terminal,
    `Merv.ReviewClaims.generation_never_decreases,
    `Merv.ReviewClaims.stale_claim_cannot_submit,
    `Merv.ReviewClaims.older_revocation_cannot_release,
    `Merv.ReviewClaims.wrong_claim_release_unchanged,
    `Merv.ReviewClaims.trace_pinned_immutable,
    `Merv.ReviewClaims.trace_submitted_terminal,
    `Merv.ReviewClaims.successful_submit_requires_current_checks,
    `Merv.SessionOwnership.trace_preserves_exclusive,
    `Merv.SessionOwnership.trace_terminal,
    `Merv.SessionOwnership.release_preserves_successor,
    `Merv.SessionOwnership.wrong_receipt_unchanged,
    `Merv.SessionOwnership.run_requires_current_generation,
    `Merv.SessionOwnership.replaced_preparation_cannot_execute,
    `Merv.SessionOwnership.expired_not_usable,
    `Merv.SessionOwnership.closed_not_usable,
    `Merv.SessionOwnership.used_run_no_effect,
    `Merv.SessionOwnership.run_consumes,
    `Merv.SessionOwnership.trace_retains_assignment,
    `Merv.WorkflowDependencies.certified_acyclic,
    `Merv.WorkflowDependencies.trace_preserves_acyclic,
    `Merv.WorkflowDependencies.removal_preserves_acyclic,
    `Merv.WorkflowDependencies.gated_requires_all_settled,
    `Merv.WorkflowDependencies.finish_requires_all_settled,
    `Merv.WorkflowDependencies.terminal_preserved,
    `Merv.WorkflowDependencies.no_op_add_keeps_revision,
    `Merv.IdentityCredentials.trace_retains_identity_expiry_revocation,
    `Merv.IdentityCredentials.empty_trace_bounded,
    `Merv.IdentityCredentials.adopt_existing_unchanged,
    `Merv.IdentityCredentials.unknown_revoke_no_tombstone,
    `Merv.IdentityCredentials.renewal_owner_only,
    `Merv.IdentityCredentials.revocation_owner_only,
    `Merv.IdentityCredentials.expired_renewal_unchanged,
    `Merv.IdentityCredentials.authenticate_iff,
    `Merv.IdentityCredentials.revoked_never_authenticates,
    `Merv.ScopeAuthority.worker_permission_subset,
    `Merv.ScopeAuthority.worker_never_operator,
    `Merv.ScopeAuthority.arbitrary_trace_epoch_invalidation,
    `Merv.ScopeAuthority.removal_invalidates_arbitrary_future,
    `Merv.ScopeAuthority.role_change_invalidates_arbitrary_future,
    `Merv.ScopeAuthority.trace_fresh_epochs,
    `Merv.ScopeAuthority.delegated_project_binding,
    `Merv.ScopeAuthority.key_authority_requires_current_membership,
    `Merv.ScopeAuthority.project_key_cannot_cross_project,
    `Merv.ScopeAuthority.human_jwt_expiry_denied,
    `Merv.ScopeAuthority.service_requires_same_project_and_writer,
    `Merv.ScopeAuthority.trusted_review_service_exception,
    `Merv.Fleet.trace_reservation_bounds,
    `Merv.Fleet.trace_allocation_identity,
    `Merv.Fleet.trace_create_launch_identity,
    `Merv.Fleet.trace_receipt_identity,
    `Merv.Fleet.trace_stop_released_monotone,
    `Merv.Fleet.admission_fences,
    `Merv.Fleet.ambiguous_keeps_capacity,
    `Merv.Fleet.concurrent_refusal_keeps_capacity,
    `Merv.FleetWorkflow.trace_retirement_safe,
    `Merv.FleetWorkflow.claim_requires_epoch,
    `Merv.FleetWorkflow.idle_read_stop_counterexample,
    `Merv.FleetWorkflow.idle_read_conditional_retirement,
    `Merv.FleetWorkflow.retirement_checks_capture,
    `Merv.FleetLease.trace_conservative_evidence,
    `Merv.FleetLease.trace_original_lease,
    `Merv.FleetLease.observed_highwater,
    `Merv.FleetLease.unknown_never_times_out,
    `Merv.FleetLease.replacement_lease_counterexample,
    `Merv.FleetLease.trace_release_iff_terminal,
    `Merv.FleetLease.attempted_retained_without_terminal,
    `Merv.FleetLease.arbitrary_time_never_releases,
    `Merv.FleetLease.step_clears_legacy_deadline,
    `Merv.FleetLease.terminal_recovery,
    `Merv.FleetLease.terminal_retention,
    `Merv.FleetLease.stale_deadline_cannot_release,
    `Merv.FleetRelease.trace_safe,
    `Merv.FleetRelease.arbitrary_trace_live_requires_reservation,
    `Merv.FleetRelease.released_pending_requires_tombstone,
    `Merv.FleetRelease.trace_release_evidence,
    `Merv.FleetRelease.materialized_release_requires_terminal,
    `Merv.FleetRelease.trace_original_identity,
    `Merv.FleetRelease.trace_tombstone_absorbing,
    `Merv.FleetRelease.trace_release_retained,
    `Merv.FleetRelease.terminal_observation_then_release,
    `Merv.FleetRelease.never_attempted_release,
    `Merv.FleetRelease.sole_refusal_no_pending,
    `Merv.FleetRelease.sole_no_effect_refusal_releases,
    `Merv.FleetRelease.concurrent_refusal_keeps_capacity,
    `Merv.FleetRelease.old_timeout_late_create_counterexample,
    `Merv.FleetRelease.fixed_rule_allows_late_effect_but_holds_reservation,
    `Merv.FleetRelease.concurrent_first_refusal_trace,
    `Merv.FleetRelease.same_key_recovery_after_lost_reply,
    `Merv.FleetRelease.delayed_create_after_terminal_is_tombstoned,
    `Merv.FleetRelease.delayed_renew_keeps_live_reservation,
    `Merv.FleetRelease.delayed_renew_after_terminal_cannot_revive,
    `Merv.FleetRelease.attempted_without_evidence_retains,
    `Merv.FleetRelease.disconnected_cannot_queue,
    `Merv.FleetRelease.wrong_identity_cannot_queue,
    `Merv.RunnerOwnership.arbitrary_trace_safe,
    `Merv.RunnerOwnership.at_most_one_worker_start,
    `Merv.RunnerOwnership.at_most_one_claim_and_owner,
    `Merv.RunnerOwnership.pin_precedes_start,
    `Merv.RunnerOwnership.pin_precedes_owner_creation,
    `Merv.RunnerOwnership.terminal_preserved,
    `Merv.RunnerOwnership.uncertain_cannot_claim,
    `Merv.RunnerOwnership.pinned_replay_no_effect,
    `Merv.RunnerOwnership.exact_launch_replay,
    `Merv.RunnerOwnership.conflicting_launch_replay,
    `Merv.RunnerOwnership.claim_wins,
    `Merv.RunnerOwnership.cancellation_wins,
    `Merv.RunnerOwnership.pinned_timeout_is_uncertain,
    `Merv.RunnerOwnership.no_pin_timeout_has_no_worker,
    `Merv.RunnerOwnership.arbitrary_trace_pin_retained,
    `Merv.RunnerOwnership.guarded_no_pin_timeout,
    `Merv.RunnerOwnership.known_different_boot_ends,
    `Merv.RunnerOwnership.unproven_exit_is_uncertain,
    `Merv.RunnerSettlement.completion_marker_blocks_attempt,
    `Merv.RunnerSettlement.crash_window_repeats_call,
    `Merv.RunnerSettlement.arbitrary_trace_completed_debts,
    `Merv.RunnerSettlement.arbitrary_trace_settlement_safe,
    `Merv.RunnerSettlement.uncertain_cannot_settle]
  for name in required do
    match (← getConstInfo name) with
    | .thmInfo _ => pure ()
    | _ => throwError "Expected a proved theorem: {name}"
  let allowed : Array Name := #[`propext, `Classical.choice, `Quot.sound]
  let mut audited : Nat := 0
  for (name, _) in (← getEnv).constants.toList do
    if `Merv |>.isPrefixOf name then
      for dependency in (← collectAxioms name) do
        unless allowed.contains dependency do
          throwError "Disallowed axiom {dependency} in {name}"
      audited := audited + 1
  if audited == 0 then throwError "No model declarations were audited"
  logInfo m!"Axiom audit passed: {audited} model declarations; {required.size} required theorems"
